export {
  authMe,
  blockUser,
  cancelMyEmailChange,
  deleteMyAccount,
  getBlockedUsers,
  getUserSuggestions,
  searchUserByUserName,
  sendEmailChangeOtp,
  test,
  unblockUser,
  updateMe,
  updatePreferences,
  uploadAvatar,
  verifyMyEmailChange,
} from "../modules/user-profile/api/http/user.controller.js";
