export const APP_ROLES = {
  USER: "USER",
  SUPPORT: "SUPPORT",
  MODERATOR: "MODERATOR",
  ADMIN: "ADMIN",
  SUPER_ADMIN: "SUPER_ADMIN",
};

export const APP_PERMISSIONS = {
  DASHBOARD_VIEW: "DASHBOARD_VIEW",
  USER_VIEW: "USER_VIEW",
  USER_LOCK: "USER_LOCK",
  USER_UNLOCK: "USER_UNLOCK",
  USER_DELETE: "USER_DELETE",
  ROLE_VIEW: "ROLE_VIEW",
  ROLE_ASSIGN: "ROLE_ASSIGN",
  PERMISSION_VIEW: "PERMISSION_VIEW",
  REPORT_VIEW: "REPORT_VIEW",
  REPORT_HANDLE: "REPORT_HANDLE",
  SUPPORT_VIEW: "SUPPORT_VIEW",
  SUPPORT_REPLY: "SUPPORT_REPLY",
  MAINTENANCE_TOGGLE: "MAINTENANCE_TOGGLE",
  AUDIT_LOG_VIEW: "AUDIT_LOG_VIEW",
};

export const ROLE_PRIORITY = [
  APP_ROLES.SUPER_ADMIN,
  APP_ROLES.ADMIN,
  APP_ROLES.MODERATOR,
  APP_ROLES.SUPPORT,
  APP_ROLES.USER,
];

export const ROLE_LEVEL_MAP = {
  [APP_ROLES.USER]: 20,
  [APP_ROLES.SUPPORT]: 40,
  [APP_ROLES.MODERATOR]: 60,
  [APP_ROLES.ADMIN]: 80,
  [APP_ROLES.SUPER_ADMIN]: 100,
};

export const ROLE_LABEL_MAP = {
  [APP_ROLES.USER]: "Nguoi dung",
  [APP_ROLES.SUPPORT]: "Ho tro",
  [APP_ROLES.MODERATOR]: "Kiem duyet",
  [APP_ROLES.ADMIN]: "Admin",
  [APP_ROLES.SUPER_ADMIN]: "Super Admin",
};

export const ROLE_PERMISSION_MAP = {
  [APP_ROLES.USER]: [],
  [APP_ROLES.SUPPORT]: [
    APP_PERMISSIONS.SUPPORT_VIEW,
    APP_PERMISSIONS.SUPPORT_REPLY,
  ],
  [APP_ROLES.MODERATOR]: [
    APP_PERMISSIONS.USER_VIEW,
    APP_PERMISSIONS.REPORT_VIEW,
    APP_PERMISSIONS.REPORT_HANDLE,
  ],
  [APP_ROLES.ADMIN]: [
    APP_PERMISSIONS.DASHBOARD_VIEW,
    APP_PERMISSIONS.USER_VIEW,
    APP_PERMISSIONS.USER_LOCK,
    APP_PERMISSIONS.USER_UNLOCK,
    APP_PERMISSIONS.USER_DELETE,
    APP_PERMISSIONS.ROLE_VIEW,
    APP_PERMISSIONS.ROLE_ASSIGN,
    APP_PERMISSIONS.PERMISSION_VIEW,
    APP_PERMISSIONS.REPORT_VIEW,
    APP_PERMISSIONS.REPORT_HANDLE,
    APP_PERMISSIONS.SUPPORT_VIEW,
    APP_PERMISSIONS.SUPPORT_REPLY,
    APP_PERMISSIONS.MAINTENANCE_TOGGLE,
    APP_PERMISSIONS.AUDIT_LOG_VIEW,
  ],
  [APP_ROLES.SUPER_ADMIN]: Object.values(APP_PERMISSIONS),
};
