export const SOCKET_ROOMS = {
  ADMINS: "admins",
};

export const USER_SOCKET_EVENTS = {
  REGISTER: "user:register",
  LOGIN: "user:login",
  LOGOUT: "user:logout",
  ONLINE: "user:online",
  OFFLINE: "user:offline",
  STATUS_CHANGED: "user:status-changed",
  ACCOUNT_LOCKED: "user:account-locked",
  ACCOUNT_UNLOCKED: "user:account-unlocked",
  ROLE_UPDATED: "user:role-updated",
  ACCOUNT_DELETED: "account:deleted",
  ACCOUNT_BANNED_LEGACY: "account:banned",
  SUPPORT_REPLY_NEW: "support:reply:new",
  REPORT_STATUS_UPDATED: "report:status-updated",
  SYSTEM_MAINTENANCE_ON: "system:maintenance:on",
  SYSTEM_MAINTENANCE_OFF: "system:maintenance:off",
  MAINTENANCE_MODE_LEGACY: "maintenance-mode",
};

export const ADMIN_SOCKET_EVENTS = {
  USER_NEW: "admin:user:new",
  USER_LOGIN: "admin:user:login",
  USER_LOGOUT: "admin:user:logout",
  USER_STATUS_CHANGED: "admin:user:status-changed",
  USER_LOCKED: "admin:user:locked",
  USER_UNLOCKED: "admin:user:unlocked",
  USER_DELETED: "admin:user:deleted",
  USER_ROLE_UPDATED: "admin:user-role-updated",
  SUPPORT_NEW_MESSAGE: "admin:support:new-message",
  REPORT_NEW: "admin:report:new",
  REPORT_UPDATED: "admin:report:updated",
  DASHBOARD_STATS_UPDATED: "admin:dashboard:stats-updated",
  SYSTEM_NOTIFICATION: "admin:system:notification",
  MAINTENANCE_ON: "admin:maintenance:on",
  MAINTENANCE_OFF: "admin:maintenance:off",
};

export const CALL_SOCKET_EVENTS = {
  INVITE: "call:invite",
  ACCEPT: "call:accept",
  REJECT: "call:reject",
  CANCEL: "call:cancel",
  END: "call:end",
  OFFER: "call:offer",
  ANSWER: "call:answer",
  ICE_CANDIDATE: "call:ice-candidate",
  INCOMING: "call:incoming",
  ACCEPTED: "call:accepted",
  REJECTED: "call:rejected",
  CANCELLED: "call:cancelled",
  ENDED: "call:ended",
  MISSED: "call:missed",
  BUSY: "call:busy",
  ERROR: "call:error",
  GROUP_START: "group-call:start",
  GROUP_JOIN: "group-call:join",
  GROUP_DECLINE: "group-call:decline",
  GROUP_LEAVE: "group-call:leave",
  GROUP_END: "group-call:end",
  GROUP_OFFER: "group-call:offer",
  GROUP_ANSWER: "group-call:answer",
  GROUP_ICE_CANDIDATE: "group-call:ice-candidate",
  GROUP_SYNC_STATE: "group-call:sync-state",
  GROUP_INCOMING: "group-call:incoming",
  GROUP_STARTED: "group-call:started",
  GROUP_PARTICIPANT_JOINED: "group-call:participant-joined",
  GROUP_PARTICIPANT_LEFT: "group-call:participant-left",
  GROUP_PARTICIPANT_DECLINED: "group-call:participant-declined",
  GROUP_PARTICIPANT_MISSED: "group-call:participant-missed",
  GROUP_ENDED: "group-call:ended",
  GROUP_CLEANED: "group-call-cleaned",
  GROUP_STATE: "group-call:state",
  GROUP_BUSY: "group-call:busy",
  GROUP_ERROR: "group-call:error",
};
